### ISSUE TITLE
Single time point image stack

### ISSUE THREAD

**Issue by jlinsley1983** [drewlinsley/GEDI#5]
Single time point image stack

Need to be able to run both test_vgg16_placeholder.py and training_vgg16_placeholder.py using a single image rather than a stack of more than 1 image. Currently get the error "IndexError: too many indices for array" when tif image file has only one image in stack (even though at this point we only use the first image anyway). Would be ideal if it could read input of one or more than one image in stack.

**Comment by drewlinsley** [comment]
Added a temporary fix.

**Comment by jlinsley1983** [comment]
Works now on single images, but still gives warning: "Warning: Image has no slices.If a single time point was passed, ignore this message." that is unnecessary.

**Comment by drewlinsley** [comment]
Fixed.
